server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1
  application:
    name: ms-registry

logging:
  file:
    name: ${LOG_URL:./ms-registry.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    level: ${LOG_LEVEL:DEBUG}
